"""
Station search and interactive selection helpers for MF and ISD sources.

Covers both Météo-France DPClim (mf_stations.csv) and NOAA ISD sources.
All user-facing I/O (print / input) is concentrated here so that the API
client classes stay free of UI concerns.

Author:  Samy KRAIEM
Created: 2024
Updated: 2026
"""

import logging
import math
import os
import sys

import numpy as np
import pandas as pd

from src.utils import parse_coord, resource_path

logger = logging.getLogger(__name__)

MF_STATIONS_CSV = resource_path(os.path.join("weather_stations_infos", "mf_stations.csv"))


def load_mf_stations() -> pd.DataFrame:
    """Load mf_stations.csv generated by fetch_mf_stations.py.

    Returns:
        pd.DataFrame: Station catalogue with numeric Latitude, Longitude,
            and Altitude columns.

    Raises:
        SystemExit: If the catalogue file is not found.
    """
    if not os.path.exists(MF_STATIONS_CSV):
        logger.error(
            "Station catalogue '%s' not found. "
            "Run fetch_mf_stations.py first to generate it.",
            MF_STATIONS_CSV,
        )
        sys.exit(1)
    df = pd.read_csv(MF_STATIONS_CSV, dtype={'ID': str})
    for col in ('Latitude', 'Longitude', 'Altitude'):
        df[col] = pd.to_numeric(df[col], errors='coerce')
    logger.info("Station catalogue loaded — %d stations.", len(df))
    return df


def display_mf_stations(df: pd.DataFrame) -> None:
    """Print a numbered table of Météo-France stations to stdout.

    Args:
        df (pd.DataFrame): Station rows to display.  If a *distance_km*
            column is present it is appended to each line.
    """
    has_dist = 'distance_km' in df.columns
    print()
    for idx, row in df.iterrows():
        date_fin = (
            str(row['DateFin'])[:10]
            if pd.notna(row.get('DateFin')) and str(row.get('DateFin', '')) not in ('nan', '')
            else 'present'
        )
        dist_str = f"  {row['distance_km']:>7.1f} km" if has_dist else ""
        print(
            f"  [{idx:>2}]  {str(row['ID']):<12}  {str(row['Nom']):<42}"
            f"  alt {row['Altitude']:>5.0f} m"
            f"  {str(row['DateDebut'])[:10]}–{date_fin}"
            f"{dist_str}"
        )


def select_mf_by_name(df: pd.DataFrame) -> str:
    """Search Météo-France stations by name substring and return the selected ID.

    Args:
        df (pd.DataFrame): Full station catalogue loaded from mf_stations.csv.

    Returns:
        str: Station ID chosen by the user.
    """
    while True:
        query = input("\nStation name search: ").strip()
        hits  = df[df['Nom'].str.contains(query, case=False, na=False)].reset_index(drop=True)
        if hits.empty:
            logger.warning("No match for '%s'. Try again.", query)
            continue
        if len(hits) > 30:
            logger.warning("%d matches — refine your query (max 30 shown).", len(hits))
            hits = hits.iloc[:30].reset_index(drop=True)
        break

    display_mf_stations(hits)

    if len(hits) == 1:
        logger.info("Single match — auto-selected.")
        return str(hits.iloc[0]['ID'])

    valid = list(hits.index)
    while True:
        raw = input(f"\nSelect index (0–{valid[-1]}): ").strip()
        try:
            idx = int(raw)
            if idx in valid:
                return str(hits.loc[idx]['ID'])
        except ValueError:
            pass
        print("  Invalid index, please retry.")


def select_mf_nearest(df: pd.DataFrame) -> str:
    """Find the nearest Météo-France stations by coordinates and return the selected ID.

    Prompts the user for latitude and longitude, computes Haversine distances
    to the 10 closest stations, and returns the user-selected station ID.

    Args:
        df (pd.DataFrame): Full station catalogue loaded from mf_stations.csv.

    Returns:
        str: Station ID chosen by the user.
    """
    print("  (accepted formats: 48.85  /  48,85  /  44,38°N  /  4,64°E)")
    while True:
        try:
            lat = parse_coord(input("\nLatitude  : "))
            lon = parse_coord(input("Longitude : "))
            if not (-90 <= lat <= 90) or not (-180 <= lon <= 180):
                print("  Out-of-range coordinates. Please retry.")
                continue
            break
        except ValueError as exc:
            print(f"  {exc}. Please retry.")

    valid_df = df.dropna(subset=['Latitude', 'Longitude'])
    lat_r = math.radians(lat)
    lon_r = math.radians(lon)
    dlat  = np.radians(valid_df['Latitude'].values)  - lat_r
    dlon  = np.radians(valid_df['Longitude'].values) - lon_r
    a     = (np.sin(dlat / 2) ** 2
             + math.cos(lat_r) * np.cos(np.radians(valid_df['Latitude'].values))
             * np.sin(dlon / 2) ** 2)
    dist  = 6371.0 * 2.0 * np.arcsin(np.sqrt(a))

    nearest = valid_df.copy()
    nearest['distance_km'] = dist
    nearest = nearest.nsmallest(10, 'distance_km').reset_index(drop=True)

    display_mf_stations(nearest)

    valid = list(nearest.index)
    while True:
        raw = input(f"\nSelect index (0–{valid[-1]}): ").strip()
        try:
            idx = int(raw)
            if idx in valid:
                return str(nearest.loc[idx]['ID'])
        except ValueError:
            pass
        print("  Invalid index, please retry.")


def select_mf_from_dept(stations: list) -> str:
    """Display a department station list and return the user-selected station ID.

    Args:
        stations (list): List of station dicts returned by
            Client.get_stations_list() (each dict has at least 'id' and 'nom').

    Returns:
        str: Station ID chosen by the user.
    """
    logger.info("Stations available for the department (ID : NAME):")
    valid_ids = {str(s['id']) for s in stations}
    for s in stations:
        logger.info("  %s : %s", s['id'], s['nom'])
    selected_id = input("\nEnter wanted station ID: ").strip()
    while selected_id not in valid_ids:
        logger.warning("ID '%s' not in the list. Please try again.", selected_id)
        selected_id = input("Enter wanted station ID: ").strip()
    return selected_id


def select_isd_station(stations: pd.DataFrame) -> pd.Series:
    """Display an ISD station DataFrame and return the user-selected row.

    Args:
        stations (pd.DataFrame): Candidate stations, optionally with a
            *distance_km* column added by ISDClient.find_nearest_stations().

    Returns:
        pd.Series: The row corresponding to the station chosen by the user.

    Raises:
        ValueError: If *stations* is empty.
    """
    if stations.empty:
        raise ValueError("Empty station list — nothing to select.")

    has_dist = 'distance_km' in stations.columns
    print()
    for idx, row in stations.iterrows():
        b = str(int(row['BEGIN']))[:4] if pd.notna(row['BEGIN']) else '?'
        e = str(int(row['END']))[:4]   if pd.notna(row['END'])   else '?'
        dist_str = f"  {row['distance_km']:>7.1f} km" if has_dist else ""
        print(
            f"  [{idx:>2}]  {str(row['STATION NAME']):<42}  {str(row['CTRY']):<4}"
            f"  lat {row['LAT']:>7.3f}  lon {row['LON']:>8.3f}"
            f"  alt {row['ELEV(M)']:>6.1f} m  {b}–{e}{dist_str}"
        )

    if len(stations) == 1:
        logger.info("Single match — auto-selected.")
        return stations.iloc[0]

    valid = list(stations.index)
    while True:
        raw = input(f"\nSelect station index (0–{valid[-1]}): ").strip()
        try:
            idx = int(raw)
            if idx in valid:
                break
        except ValueError:
            pass
        print("  Invalid index, please retry.")

    selected = stations.loc[idx]
    logger.info("Selected: %s  (%s)", selected['STATION NAME'], selected['CTRY'])
    return selected
